name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        nkro: [enabled, disabled]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: smk
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: Setup
      run: nix develop --command meson setup build -Dnkro=${{ matrix.nkro }}
    - name: Build
      run: nix develop --command meson compile -C build
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: smk-${{ matrix.nkro == 'enabled' && 'nkro' || '6kro' }}
        path: build/*.hex

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: smk
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: Setup
      run: nix develop --command meson setup build
    - name: Lint
      run: nix develop --command ninja -C build clang-format-check

